### ISSUE TITLE
Add C++ implementation of the Mandelbrot algorithm

### ISSUE THREAD

**Issue by lemorage** [jramb/mandelbrot#1]
I noticed that the repository currently lacks a C++ implementation of the Mandelbrot algorithm. Have you considered adding a C++ implementation before? If possible, I would like to create a PR to add the C++ implementation of the Mandelbrot algorithm.

**Comment by jramb** [comment]
Haha, well, no, I have not considered C++ yet. TBH it is not on my personal TOLEARN list even.
Anyway it is not that I want to compete with Rosetta Code, have a look here:
https://rosettacode.org/wiki/Mandelbrot_set#C++

**Comment by lemorage** [comment]
@jramb Great, totally understand. BTW, the link is tremendously surprising. Cheers!
